### PR TITLE
Update etcd versions

### PR DESCRIPTION
**Pull request by leahnp**
Initial work for: https://github.com/samsung-cnct/k2/issues/620

### CODE REVIEW

**Comment by mikeln** [comment]
Why not etcd 3.2.x (i.e. 3.2.4 currently)?

**Comment by leahnp** [comment]
I was just following the k8s community cluster recs - but no reason not to get on the latest.

**Comment by mikeln** [comment]
well, I'm not sure of the differences btwn 3.1.x and 3.2.x there may be some reason not to do it...

**Comment by davidewatson** [comment]
According to the [etcd upgrade instructions](https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_2.md) 

> 3.2 introduces two breaking changes.

This noteworthy, because it is a minor version change. Since the breaking changes are in the client and we vendor our golang dependencies, it doesn't affect us.

**Comment by davidewatson** [comment]
According to the [etcd upgrade instructions](https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_2.md) 

> 3.2 introduces two breaking changes.

This noteworthy, because it is a minor version change. However, since the breaking changes are in the client and we vendor our golang dependencies, it doesn't affect us.

**Comment by countspongebob** [comment]
I've opened possibly a dup here

https://github.com/samsung-cnct/kraken/issues/206

@leahnp The reason "not to update to latest" is that we lose community CI alignment, support, and protection. On core kubernetes we should not be running ahead of community on core.

**Pull request merged**
