### PR TITLE
remove extraneous space

### PR DESCRIPTION
**Pull request by mikeln**
Emergency fix

### CODE REVIEW

**Comment by sostheim** [comment]
LGTM

**Comment by mikeln** [comment]
still a worry... how did that PR  #622 pass CI in the first place?  The erroneous space is there.

**Comment by mikeln** [comment]
In flight PRs should rebase after this, to get the increased timeout needed because of the serialization of the etcd node initialization before the regular nodes.

**Comment by mikeln** [comment]
(can someone use the "review" button to approve pls)

**Pull request merged**
