### PR TITLE
Corrected namsepace to namespace

### PR DESCRIPTION
**Pull request by joejulian**
nam~~sepace~~este

### CODE REVIEW

**Comment by DStorck** [comment]
nice catch :)

**Comment by joejulian** [comment]
Credit to @guineveresaenger for actually noticing it.

**Comment by coffeepac** [comment]
we should have let CI run here.  the run is queued up on pipelet now.

**Comment by guineveresaenger** [comment]
Butts. I forgot about that. Should I revert?

**Comment by coffeepac** [comment]
no, this is a small change.  one time pass.

**Comment by joejulian** [comment]
Not this time. Next time though.

**Comment by guineveresaenger** [comment]
Phew. I got too excited. My bad.

**Pull request merged**
