### PR TITLE
Git 99 remove etc autoscaling

### PR DESCRIPTION
**Pull request by coffeepac**
This + https://github.com/samsung-cnct/k2/issues/105 resolves https://github.com/samsung-cnct/k2/issues/99.  

This PR removes all of the dynamic resizing of etcd nodes in favor of individually creating a static set of nodes. 

/cc @maratoid @venezia

### CODE REVIEW

**Comment by davidewatson** [comment]
Agreed.

**Comment by coffeepac** [comment]
argh, I see the problem.  I used the wrong list for calculating the index into an array.  Testing a fix now.

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
farging tiller deploy flakes

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
tiller flake has hit both AWS and GKE on different runs.  right, gotta sort that out.

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
Thanks @l337ch.  And its not the ASG that was causing the problem.  It was the lambda function and other associated pieces that was causing the issues.  We may reinstate the ASG later but for now we need stability.

**Pull request merged**
