### PR TITLE
More reliable string slicing for k8s minor version aws fact

### PR DESCRIPTION
**Pull request by guineveresaenger**
This makes sure that we will always slice right before the second dot, no matter how many digits in the version string.

### CODE REVIEW

**Comment by coffeepac** [comment]
ok to test

**Comment by coffeepac** [comment]
can you rebase this against master?  there are some extra commits that I think are already in master

**Comment by guineveresaenger** [comment]
Should be rebased now. Sorry about that!

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
@yenicapotediaz can you clean up the commit history on this one?  you seem to have picked up a whole bunch of commits not from your branch.

**Comment by coffeepac** [comment]
retest this please

**Pull request closed without merging**
