### PR TITLE
Fold kubeVersion schema into kubeVersionedConfig.

### PR DESCRIPTION
**Pull request by davidewatson**

### CODE REVIEW

**Comment by davidewatson** [comment]
A customer suggested the previous organization contained one too many levels of redirection, leading to confusion, and upset. They were right.

**Comment by davidewatson** [comment]
Another benefit of this is the autogenerated documentation becomes clearer as well.

**Comment by alejandroEsc** [comment]
Lgtm

**Comment by davidewatson** [comment]
`Also:   java.io.IOException: Pipe not connected` Putting this one back thru the wringer.

**Comment by davidewatson** [comment]
`Also:   java.io.IOException: Pipe not connected` again, this time during GKE. AWS passed just fine.

**Pull request merged**
