### PR TITLE
made string slicing for aws k8s minor version more reliable

### PR DESCRIPTION
**Pull request by yenicapotediaz**

### CODE REVIEW

**Comment by coffeepac** [comment]
ok to test

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
@yenicapotediaz I've been retesting this for a few days and I've never gotten it to go through.  Can you take a look at this and make sure it passes a normal up process?  Its starting to seem like there's a something off.

**Comment by yenicapotediaz** [comment]
Ok, I'll check it out.

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
LGTM

**Pull request merged**
