### PR TITLE
Fix dryrun for flannel tasks

### LINKED ISSUE #327: dryrun currently fails
During development it is common to make changes and then partially test them by setting the dryrun tag. In particular this will skip the provider role, so that the developer does not have to wait for the cluster to be brought up. Currently dryrun is broken in that it fails during the fabric role. [1]

This can be partially fixed by fixing #229, but then the fabric role retries 100 times and fails, because this is a dryrun! The simplest fix is to remove the dryrun tag from the fabric role. But then dryrun could not be used to test fabric templating. That maybe acceptable.

[1]

```
TASK [/root/Samsung/k2/ansible/roles/kraken.fabric/kraken.fabric.flannel : Wait for api server to become available in case it's not] ***
task path: /root/Samsung/k2/ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml:15
 [WARNING]: Unable to find '/root/.kraken/lp-k2recon/admin.kubeconfig' in expected paths.

fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /root/.kraken/lp-k2recon/admin.kubeconfig"
}
```

For further information about which tags k2 makes available, see [up.sh](https://github.com/samsung-cnct/k2/blob/master/ansible/up.yaml)

### PR DESCRIPTION
**Pull request by joejulian**
Partially fixes #327

### CODE REVIEW

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
@coffeepac Just moved it into a var instead of setting a fact. Setting a var where that data is actually used makes the code easier to read, unless that fact is going to be used elsewhere.

**Comment by joejulian** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by davidewatson** [comment]
Tiller failed to come up: https://pipelet.kubeme.io/job/k2-pr/496/

**Comment by joejulian** [comment]
Yes, I was noticing that. Strange.

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Pull request merged**
