### PR TITLE
K2recon

### PR DESCRIPTION
**Pull request by coffeepac**
This contains all of the changes from the k2recon branch rebased onto current master for a clean merge.

### CODE REVIEW

**Comment by mikeln** [comment]
retest this please

**Comment by mikeln** [comment]
retest this please

**Comment by mikeln** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by mikeln** [comment]
OK..finally.
Let's break everyone.!

**Pull request merged**
