### PR TITLE
Fix walk of status object when killing services

### PR DESCRIPTION
**Pull request by NathanZook**

### CODE REVIEW

**Comment by NathanZook** [comment]
retest this please

**Comment by DStorck** [comment]
Looks good.

**Comment by joejulian** [comment]
```
The vpc 'vpc-359b035c' has dependencies and cannot be deleted.
```
That _could_ be a service that wasn't removed and could be related to this PR. Please take a look.

**Comment by NathanZook** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
add to whitelist

**Pull request merged**
