### PR TITLE
I submit for your approval setting verbosity for ansible 

### PR DESCRIPTION
**Pull request by alejandroEsc**
via a -v, let me know what you think and we can address it in a different manner if you wish.

example:

```
 ./up.sh -o ~/.kraken/ -c ~/.kraken/ae-cynosure_config.yaml -t 'ssh' -v '-vvv'
```

### CODE REVIEW

**Comment by alejandroEsc** [comment]
sounds good to me, ill attempt to do so and ill approach you if i cannot figure how to hook things up.

**Comment by alejandroEsc** [comment]
is it possible to retest this?

**Comment by coffeepac** [comment]
test this please

**Comment by coffeepac** [comment]
test this please

**Comment by coffeepac** [comment]
test this please

**Comment by coffeepac** [comment]
@alejandroEsc you will need to rebase this PR against master.  it won't pass CI on its own.

**Pull request merged**
