### PR TITLE
upgrade drunkensmee to v0.5

### PR DESCRIPTION
**Pull request by coffeepac**
this will let us use k2 in us-east-2

### CODE REVIEW

**Comment by coffeepac** [comment]
@joejulian tagged you on this for review.  would love to get it through today.

**Comment by coffeepac** [comment]
test this please

**Comment by joejulian** [comment]
test this please

**Comment by coffeepac** [comment]
I'm going to merge this as the associated kraken-ci-jobs PR was already merged.  the associated PR (samsung-cnct/kraken-ci-jobs#167) forces all CI jobs to run in us-east-2 and they will all fail without this change.

**Pull request merged**
