### PR TITLE
helmConfig has no s

### PR DESCRIPTION
**Pull request by joejulian**

### CODE REVIEW

**Comment by coffeepac** [comment]
this is goofy, but this PR is exhibiting a dryrun bug in CI.  I have no idea why.  I'll poke it a bit.

**Comment by joejulian** [comment]
It just needs rebased on the non-broken dryrun code.

**Comment by coffeepac** [comment]
okay, its running now.  weird though, I didn't see a git history for this branch that had the busted dryrun code in it.  my eyes they are a-failin?

**Comment by joejulian** [comment]
I had rebased on master, originally, when a broken dryrun patch had been self-merged into master by a developer who shall remain nameless. Until this morning I had not rebased again after the revert.

**Comment by coffeepac** [comment]
Manual override:  have seen all steps in process succeed but not at once.  Failures are obvious jenkins issues or known k2/e2e flakes.  Merging.

**Pull request merged**
