### PR TITLE
Allow the use of Ubuntu cloud images with aws

### PR DESCRIPTION
**Pull request by joejulian**
This allows you to use defaultUbuntu instead of defaultCoreOS to boot up machines on aws.

Issue #157

### CODE REVIEW

**Comment by joejulian** [comment]
This is not ready to merge. Requires, at the very least, documentation.

**Comment by mikeln** [comment]
I would rather the Ansible format changes be in a separate PR.

**Comment by joejulian** [comment]
Ah, yep... that was my intention too. Got lost in the mix, thanks.

**Comment by joejulian** [comment]
This is failing because of configuration changes needed in the config.

**Comment by joejulian** [comment]
This actually just requires the majority of the changes in #403. Closing this in favor of that.

**Pull request closed without merging**
