### PR TITLE
better docstring description for latest_helm filter and removed extra…

### PR DESCRIPTION
**Pull request by guineveresaenger**
…neous words in run-services task

### CODE REVIEW

**Comment by guineveresaenger** [comment]
@DStorck caught some nonsense I missed on #390 and I fixed the typo as well.
It is literally just descriptions that were changed here.

**Comment by coffeepac** [comment]
ok to test

**Comment by joejulian** [comment]
retest this please

**Comment by guineveresaenger** [comment]
:/ I can't tell why these are failing....

**Comment by coffeepac** [comment]
@guineveresaenger the non-pipelet runs will never succeed.  this branch is forked from a version of master that didn't work.  

pipelet is failing because of a canal thing that joe is looking into.

@joejulian any objections to merging this PR.  its a docs only thing.  if you're using it for debugging, sure, otherwise I'd like to clean this up a bit.

**Comment by joejulian** [comment]
@coffeepac done. :+1:

**Pull request merged**
