### PR TITLE
Implement spacing standards for ansible

### PR DESCRIPTION
**Pull request by joejulian**
Fix standardize spacing.
One space after `{{` and before `}}`:
```
{{ foo }}
```

One space before and after `|`
```
foo | bar
```

### CODE REVIEW

**Comment by davidewatson** [comment]
LGTM pending tests.

**Comment by coffeepac** [comment]
@joejulian how did you perform these formats?  and if its an automated tool can you include the syntax you used to we can turn it into a CI task later?

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
@coffeepac It was a simple sed replace. Some sort of syntax checker would be nice though. Someone should file an issue.

**Comment by joejulian** [comment]
retest this please

**Pull request merged**
