### PR TITLE
Add an "until" to test the retry against

### PR DESCRIPTION
**Pull request by joejulian**
I mistakenly thought that a retries clause without an until would retry
until the command succeeded. The ansible documentation is insufficient
on this point.

### CODE REVIEW

**Comment by alejandroEsc** [comment]
could @DStorck try this branch and see if that works?

**Comment by alejandroEsc** [comment]
also, @joejulian good catch.

**Comment by davidewatson** [comment]
LGTM.

**Comment by DStorck** [comment]
LGTM

**Comment by alejandroEsc** [comment]
does the check above require  a /lgtm? with a slash?

**Comment by coffeepac** [comment]
@alejandroEsc no, but @DStorck does need to file a github official review.

**Comment by alejandroEsc** [comment]
got it, as opposed to just a comment.

**Pull request merged**
