### PR TITLE
Follow ansible standards

### PR DESCRIPTION
**Pull request by joejulian**

### CODE REVIEW

**Comment by mikeln** [comment]
LGTM  runs ok for me

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by joejulian** [comment]
retest this please

**Comment by leahnp** [comment]
LGTM - I just had one inline question, if you have the time to clarify, I would appreciate it.

**Comment by joejulian** [comment]
I would be happy to, but the question isn't showing up.

**Pull request merged**
