### PR TITLE
add a map for us regions for dns suffix setting

### LINKED ISSUE #174: vpc domain name only works in us-east-1
us-east-1 domain search is ec2.internal.  All other regions are <region>.compute.internal so we will need to expose this as a configuration parameter in the networking section.

### PR DESCRIPTION
**Pull request by coffeepac**
this resolves #174

### CODE REVIEW

**Comment by coffeepac** [comment]
retest this please

**Comment by joejulian** [comment]
Doesn't work. dhcp only uses the first entry for the domain-name. May need to key this off ~/.aws/config's region.

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by joejulian** [comment]
dhcp no longer has any domain-name configured.

**Comment by coffeepac** [comment]
thanks @joejulian good catch.

**Comment by joejulian** [comment]
LGTM
WFM

**Pull request merged**
