### PR TITLE
made 1.6.4 default

### PR DESCRIPTION
**Pull request by DStorck**
this makes 1.6.4 the default version of kubernetes.  Temporarily we are removing the central logging chart because we have not yet written the rbac specs for fluentd. This will be covered in the 0.3 milestone, and then it can be added back in.

### CODE REVIEW

**Comment by leahnp** [comment]
LGTM

**Comment by alejandroEsc** [comment]
LGTM, going to try the changes on my local config file and see if that works.

**Comment by DStorck** [comment]
Jenkinsfile has been udpated.

**Comment by alejandroEsc** [comment]
FYI, verified changes worked on my latest config file. good work!

**Pull request merged**
