### PR TITLE
updated k2 to 1.6.6

### PR DESCRIPTION
**Pull request by DStorck**

### CODE REVIEW

**Comment by joejulian** [comment]
Added a "blocked" tag as gke does not support 1.6.6 (as of the last jenkins test). Clear the blocked when gke adds 1.6.6 support.

**Comment by DStorck** [comment]
@joejulian That is weird because according to https://cloud.google.com/container-engine/release-notes, 1.6.6 is supported

**Comment by joejulian** [comment]
Maybe re-run the test. Perhaps that support has changed since the test was run.

**Comment by joejulian** [comment]
I dunno what to tell you about those guys.
> ERROR: (gcloud.container.clusters.upgrade) ResponseError: code=400, message=bad desired node version ().

**Comment by joejulian** [comment]
gke passed so I'd say this is no longer blocked.

**Pull request merged**
