### PR TITLE
Added kubernetes_minor_version fact for gke

### PR DESCRIPTION
**Pull request by yenicapotediaz**

### CODE REVIEW

**Comment by coffeepac** [comment]
ok to test

**Comment by guineveresaenger** [comment]
Jenkins console says: 
```20:11:05 fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'kraken_config.kubeAuth.authn.default_basic_user is undefined' failed. The error was: error while evaluating conditional (kraken_config.kubeAuth.authn.default_basic_user is undefined): 'dict object' has no attribute 'kubeAuth'\n\nThe error appears to have been in '/kraken/ansible/roles/kraken.config/tasks/main.yaml': line 44, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set default kubernetes basic user if not defined\n  ^ here\n"}```
This part works fine when I plug in my own credentials and run a gke cluster up and down...

**Comment by guineveresaenger** [comment]
Just realized why this test fails.
Since we changed both the default gke config file as well as K2, running the test against the old config file will obviously fail.It should be tested against the new gke config file as referenced in https://github.com/samsung-cnct/kraken-ci-jobs/pull/168.

**Comment by guineveresaenger** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Comment by coffeepac** [comment]
retest this please

**Pull request merged**
